site_name: ERP Docs
copyright: Copyright &copy; 2022 - 2022 ERP Doc Site
theme:
  name: material
  custom_dir: overrides
  logo: assets/mission-logo.png
  favicon: assets/mission-logo.png
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.sections
    - navigation.tracking
    - search.highlight
    - search.suggest
    - search.share
    - toc.follow
    - header.autohide
  palette:
    - scheme: default
      toggle: 
        #icon: material/toggle-switch-off-outline
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      toggle:
        #icon: material/toggle-switch
        icon: material/brightness-7
        name: Switch to light mode
plugins:
  - search
  - tags
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - meta  
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - footnotes
  
extra:
  generator: false
  version:
    default: latest
    provider: mike
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js

nav:
  - Home: index.md
  - Purchase:
    - purchase/index.md
    - Goods Fulfillment by Central Store: purchase/purchase-flow1.md
    - Goods Fulfillment by Central Store and Supplier: purchase/purchase-flow2.md
    - Services Fulfillment: purchase/purchase-flow3.md
  - Expense:
    - expense/index.md